#
# Makefile for the ali Remote Process Call hld dis driver(drivers/rpc/dis/Makefile)
#

obj-$(CONFIG_RPC_HLD_DIS)         += ali_rpc_hld_dis.o

ali_rpc_hld_dis-objs += ali_rpc_hld_dis_dep.o

$(obj)/ali_rpc_hld_dis_dep.o:
	cp $(obj)/ali_rpc_hld_dis.bin $(obj)/ali_rpc_hld_dis_dep.o

