#
# linux/drivers/media/dvb/frontends/ali_nim/Makefile
#

#obj-$(CONFIG_ALI_GPIO_I2C) += ali_i2c_scb.o
obj-$(CONFIG_ALI_GPIO_I2C) += ali_i2c_linux.o ali_i2c_common.o ali_i2c_compat.o
obj-$(CONFIG_ALI_GPIO_I2C) += gpio_i2c.o
