/****************************************************************************(I)(S)
 *  (C)
 *  ALi (Shanghai) Corporation, All Rights Reserved. 2010 Copyright (C)
 *  (C)
 *  File: ali_version.c
 *  (I)
 *  Description: SDK release version
 *  (S)
 *  History:(M)
 *      	Date        			Author         	Comment
 *      	====        			======		=======
 * 0.		2012.06.05			    Rodger		Create
 ****************************************************************************/
#include <linux/kernel.h>
#include <linux/of.h>
#include <version_autogenerated.h>
#include "../../../../version_autogenerated.h"
#include <linux/ali_rpc.h>

char alisee_tag[50] = "unknow";
char alisee_time[50] = "unknow";
char alicommon_tag[50] = "unknow" ;
char alicommon_time[50] = "unknow";

void see_fw_tag_get(char *see_tag,char *see_time,char *common_tag,char *common_time)
{
	u32 tag_info_desc[] =
	{
		4, DESC_OUTPUT_STRU(0,sizeof(alisee_tag)), DESC_OUTPUT_STRU(1,sizeof(alisee_time)), DESC_OUTPUT_STRU(2,sizeof(alicommon_tag)), DESC_OUTPUT_STRU(2,sizeof(alicommon_time)),
		4, DESC_P_PARA(0, 0, 0), DESC_P_PARA(0, 1, 1), DESC_P_PARA(0, 2, 2),DESC_P_PARA(0, 3, 3),
		0,
		0,
	};
    jump_to_func(NULL, ali_rpc_call, NULL, (HLD_SEEBUS_MODULE<<24)|(4<<16)|0x02, tag_info_desc);
}

void show_software_tag(void)
{
	struct device_node* node;
	const char *tag_buff,*time_buff;

	node = of_find_compatible_node(NULL, NULL, "alitech,dts-tag");
	if (NULL == node) {
	       pr_info("dts_version node is null\n");
	}
	else {
		of_property_read_string_index(node,"dts_tag",0, &tag_buff);
		of_property_read_string_index(node,"dts_built_at",0, &time_buff);
		pr_info("dts tag: %s. built at: %s.\n",tag_buff,time_buff);
	}
	pr_info("linux kernel tag: %s. built at: %s.\n",BR2_LINUX_AUTOGENERATE_VERSION,BR2_LINUX_COMPILE_DATETIME);
	pr_info("linux alicommon tag: %s. built at: %s.\n",BR2_ALICOMMON_AUTOGENERATE_VERSION,BR2_ALICOMMON_COMPILE_DATETIME);
	see_fw_tag_get(alisee_tag,alisee_time,alicommon_tag,alicommon_time);
	pr_info("alisee tag: %s. built at: %s.\n",alisee_tag,alisee_time);
	pr_info("alisee alicommon tag: %s. built at: %s.\n",alicommon_tag,alicommon_time);
}
