#
# Makefile for the ali Remote Process Call hld decv driver
#

obj-$(CONFIG_RPC_HLD_DECV)        += ali_rpc_hld_decv.o

ali_rpc_hld_decv-objs += ali_rpc_hld_decv_dep.o

$(obj)/ali_rpc_hld_decv_dep.o:
	cp $(obj)/ali_rpc_hld_decv.bin $(obj)/ali_rpc_hld_decv_dep.o

