
all:
	/opt/arm-linux-gnueabi/bin/arm-linux-gnueabi-gcc -static -EL -o mac_tool main.c tx.c 
	#gcc -o mac_tool main.c tx.c 
#	/home/mao/bt/usr/local/mips/bin/mipsel-linux-uclibc-gcc  -static -o net_test root.c
#	 cp net_test /home/martin/s3911a/sf-kernel-make/usr/busybox_1.15_d/demo_test/
#	 cp net_test /home/mao/nfs_root/demo_test/

clean:
	rm -f mac_tool
