
all:
	/opt/arm-linux-gnueabi/bin/arm-linux-gnueabi-gcc -static -EL -o phytool3921 ethpktgen.c phyrw.c main.c
#	/opt/mips-4.3/bin/mips-linux-gnu-gcc -static -EL -o nettool ethpktgen.c phyrw.c main.c
#	/opt/mipsel-4.4/bin/mipsel-linux-gnu-gcc -static -EL -o nettool main.c
#	/home/mao/bt/usr/local/mips/bin/mipsel-linux-uclibc-gcc  -static -o net_test root.c
#	 cp net_test /home/martin/s3911a/sf-kernel-make/usr/busybox_1.15_d/demo_test/
#	 cp net_test /home/mao/nfs_root/demo_test/

clean:
	rm -f phytool
