#
# Makefile for the ali Remote Process Call hld decv driver
#

obj-$(CONFIG_RPC_HLD_DECA)        += ali_rpc_hld_deca.o

ali_rpc_hld_deca-objs += ali_rpc_hld_deca_dep.o

$(obj)/ali_rpc_hld_deca_dep.o:
	cp $(obj)/ali_rpc_hld_deca.bin $(obj)/ali_rpc_hld_deca_dep.o

